CREATE DATABASE sandbox;

USE sandbox;

CREATE TABLE Users (
  id CHAR(36) NOT NULL,
  username VARCHAR(32) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password BINARY(60) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE Books (
  id CHAR(36) NOT NULL,
  user CHAR(36) NOT NULL,
  publisher VARCHAR(255) NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  cover_price DECIMAL(6,2) NOT NULL,
  page_count INT NOT NULL,
  published_at DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user) REFERENCES Users (id)
);
