CREATE DATABASE diddy-doodly-servlets DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

USE diddly-doodly-servlets;

CREATE TABLE Creators (
  id CHAR(36) NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  biography TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE Series (
  id CHAR(36) NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE Publishers (
  id CHAR(36) NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  biography TEXT NOT NULL,
  founded_at YEAR NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
