CREATE DATABASE diddy-doodly-servlets DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

USE diddly-doodly-servlets;

CREATE TABLE Creators (
  id CHAR(36) NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  biography TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE Series (
  id CHAR(36) NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE Publishers (
  id CHAR(36) NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  biography TEXT NOT NULL,
  founded_at YEAR NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE Books (
  id CHAR(36) NOT NULL,
  publisher CHAR(36) NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  cover_price DECIMAL(6, 2) NOT NULL,
  page_count INT NOT NULL,
  stratification ENUM('Books', 'Comic Books') NOT NULL,
  published_at DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (publisher) REFERENCES Publishers (id)
);

CREATE TABLE CreatorWork (
  book CHAR(36) NOT NULL,
  creator CHAR(36) NOT NULL,
  work ENUM('Writer', 'Illustrator', 'Penciller', 'Inker', 'Colorist', 'Letterer'),
  PRIMARY KEY (book, creator),
  FOREIGN KEY (book) REFERENCES Books (id),
  FOREIGN KEY (creator) REFERENCES Creators (id)
);
